[package]
name = "canvas"
version = "0.1.0"
authors = ["The wasm-bindgen Developers"]
edition = "2018"
rust-version = "1.56"

[lib]
crate-type = ["cdylib"]

[dependencies]
futures = "0.3.28"
js-sys = "0.3.64"
wasm-bindgen = "0.2.87"
wasm-timer = "0.2.5"

[dependencies.wasm-bindgen-futures]
version = "0.4.37"
features = ['futures-core']


[dependencies.web-sys]
version = "0.3.4"
features = ["CanvasRenderingContext2d", "Document", "Element", "HtmlCanvasElement", "Window", "MouseEvent", "HtmlDivElement", "HtmlLabelElement", "HtmlImageElement"]
