pub mod player_setup;
pub mod main;
pub mod army_placement;
pub mod ui_state_manager;
mod templates;
pub mod wrap_elem;
pub mod view_turn_start;
pub mod view_combat;
pub mod view_start_army_place;
pub mod view_army_place;
pub mod view_dice_roll;
pub mod view_turn;
pub mod view_game_end;
pub mod view_info;
pub mod view_label;
